# Site settings
title: Metroghar
email: goutham2027@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://metroghar.in" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
